language: node_js
sudo: false
git:
  depth: 3
node_js:
  - "4"
  - "8"
before_script:
  - npm install -g litejs
  - if [ ${TRAVIS_NODE_VERSION%%.*} = "8" ]; then npm install -g nyc coveralls; fi
script:
  - if [ ${TRAVIS_NODE_VERSION%%.*} = "8" ]; then nyc -r lcovonly -r text lj test; else lj test; fi
after_success:
  - if [ ${TRAVIS_NODE_VERSION%%.*} = "8" ]; then coveralls < coverage/lcov.info; fi

